# Generated by Django 5.0.1 on 2024-01-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hospital", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="doctor",
            old_name="special",
            new_name="speciality",
        ),
        migrations.AlterField(
            model_name="doctor",
            name="mobile",
            field=models.CharField(max_length=15),
        ),
    ]
